---

- name: Configure argo-connectors tenants - customer.conf
  ansible.builtin.template:
    src: customer.conf.j2
    dest: "{{ connector_virtenv_path }}/etc/{{ item.tenant_name | lower }}-customer.conf"
    owner: "{{ connector_owner }}"
    group: "{{ connector_group }}"
    mode: "0644"
  loop: "{{ connector_add_tenants }}"
  loop_control:
    label: "{{ item.tenant_name }}"
