---

- name: Remove tenant cron file
  ansible.builtin.file:
    path: "/etc/cron.d/{{ item | lower }}"
    state: absent
  loop: "{{ connector_remove_tenants }}"
  loop_control:
    label: "{{ item }}"
  notify: Reload cron daemon
