---

- name: Set up configuration files for added tenants
  ansible.builtin.include_tasks: ./conf-setup-add.yml
  when: connector_add_tenants | length > 0

- name: Remove configuration files for removed tenants
  ansible.builtin.include_tasks: ./conf-setup-remove.yml
  when: connector_remove_tenants | length > 0

- name: Set up cron jobs for added tenants
  ansible.builtin.include_tasks: ./cron-setup-add.yml
  when: connector_add_tenants | length > 0

- name: Remove cron jobs for removed tenants
  ansible.builtin.include_tasks: ./cron-setup-remove.yml
  when: connector_remove_tenants | length > 0
