---

- name: Set up configuration files
  ansible.builtin.import_tasks: ./conf-setup.yml


- name: Set up cron jobs
  ansible.builtin.import_tasks: ./cron-setup.yml


- name: Remove tenants
  ansible.builtin.import_tasks: ./remove_tenants.yml
  when: is_installed and connector_remove_tenants
