[project]
name = "argo-automation-cpas"
dynamic = ["version"]
license = "Apache-2.0"
readme = "README.md"
authors = [
	{ name = "Daniel Vrcic", email ="daniel.vrcic@gmail.com" }
]
description = "Automation service for the dynamic configuration of ARGO components: Connectors, POEM, Archiver and Sensu (CPAS)."
dependencies = [
	"aiohttp==3.11.0",
	"ansible-runner==2.4.0",
    "ansible-core==2.20.4",
	"argo-ams-library",
	"pyyaml",
	"ansible (>=13.5.0,<14.0.0)",
	"gitpython",
	"pytest (>=9.1.1,<10.0.0)",
	"pytest-asyncio (>=1.4.0,<2.0.0)",
    "pytest-mock"
]
requires-python = ">=3.12"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
aiohttp = "*"
ansible-core = "*"
ansible-runner = "*"
argo-ams-library = "*"

[tool.poetry.group.devel.dependencies]
ruff = "^0.11.0"
build = "*"
pdbpp = "*"
setuptools = "^82.0.1"
pytest = "*"
pytest-mock = "*"

[project.scripts]
argo-cpas = "argo_automation_cpas.cli.argo_cpas:main"
argo-cpasd = "argo_automation_cpas.cli.argo_cpasd:main"

[tool.ruff]
line-length = 100
target-version = "py312"

[tool.setuptools]
packages = [
	'argo_automation_cpas',
	'argo_automation_cpas.cli',
]

[tool.setuptools.package-dir]
argo_automation_cpas = "modules/"
"argo_automation_cpas.cli" = "cli/"

[tool.setuptools.data-files]
"" = ["pyproject.toml", "poetry.lock"]
"etc" = [
	"config/argo-cpas.conf.template",
	"config/roles-defaults.yml",
]
"usr/lib/systemd/system" = ["init/argo-cpasd.service"]
"etc/logrotate.d" = ["logrotate/logfile"]
"var/log" = ["var/log/.keep"]
"var/cache" = ["var/cache/.keep"]
"var/spool" = ["var/spool/.keep"]
"ansible/project" = [
	"ansible/project/ansible.cfg",
	"ansible/project/init.yml",
	"ansible/project/connectors.yml",
	"ansible/project/poem.yml",
]
"ansible/inventory" = [
	"ansible/inventory/connectors.ini",
	"ansible/inventory/poem.ini",
	"ansible/inventory/sensu.ini"
]
"ansible/roles/connector/defaults" = [
	"ansible/roles/connector/defaults/main.yml",
]
"ansible/roles/connector/handlers" = [
	"ansible/roles/connector/handlers/main.yml",
]
"ansible/roles/connector/tasks" = [
	"ansible/roles/connector/tasks/main.yml",
	"ansible/roles/connector/tasks/conf-setup-add.yml",
	"ansible/roles/connector/tasks/conf-setup-remove.yml",
	"ansible/roles/connector/tasks/cron-setup-add.yml",
	"ansible/roles/connector/tasks/cron-setup-remove.yml",
]
"ansible/roles/connector/templates" = [
	"ansible/roles/connector/templates/customer.conf.j2",
]
"ansible/roles/poem/defaults" = [
	"ansible/roles/poem/defaults/main.yml",
]
"ansible/roles/poem/tasks" = [
	"ansible/roles/poem/tasks/main.yml",
	"ansible/roles/poem/tasks/remove-tenants.yml",
	"ansible/roles/poem/tasks/tenant-db-tables.yml",
	"ansible/roles/poem/tasks/tenant-poem-conf.yml",
	"ansible/roles/poem/tasks/tenant-sync-superpoem-metrics.yml",
	"ansible/roles/poem/tasks/tokens-tenants-set.yml",
]

[tool.setuptools.dynamic]
version = { attr = "version.vernum" }

[tool.pytest.ini_options]
testpaths = ["tests"]
