---

- name: Playbook to configure archivers of metric results
  hosts: all
  become: true
  roles:
    - { role: archiver, archiver_owner: "{{ user_archiver }}", archiver_group: "{{ group_archiver }}" }


# vim: ft=yaml.ansible