---

- name: Playbook to configure archivers of metric results
  hosts: all
  become: true
  roles:
    - { role: archiver, owner_archiver: "{{ user_archiver }}", group_archiver: "{{ group_archiver }}" }


# vim: ft=yaml.ansible