---

- name: Playbook to configure connectors
  hosts: all
  become: true
  vars:
    errors_ignore: false
  roles:
    - { role: connector, connector_owner: "{{ connector_owner }}", connector_group: "{{ connector_group }}" }


# vim: ft=yaml.ansible
