---

- name: Set up configuration
  ansible.builtin.import_tasks: ./conf-setup.yml

- name: Metric results directory create
  ansible.builtin.import_tasks: ./dir-setup.yml

- name: Start and enable ams-consumers
  ansible.builtin.systemd_service:
    name: "ams-consumer@{{item.tenant_name}}.service"
    state: started
    enabled: true
  loop: "{{ archiver_tenants }}"