---

- name: Remove tenant ams-consumer-{tenant_name}.conf config file
  ansible.builtin.file:
    path: "{{ archiver_virtenv_path }}/etc/ams-consumer-{{ item.tenant_name }}.conf"
    state: absent
    owner: "{{ owner_archiver }}"
    group: "{{ group_archiver }}"
    mode: "0644"
  loop: "{{ archiver_remove_tenants }}"