---
- name: Remove configuration for tenants pending removal
  ansible.builtin.import_tasks: ./remove-conf-setup.yml

- name: Remove metric results directory for tenants pending removal
  ansible.builtin.import_tasks: ./remove-dir-setup.yml

- name: Stop removed ams-consumer services
  ansible.builtin.systemd_service:
    name: "ams-consumer@{{ item.tenant_name }}.service"
    state: stopped
  failed_when: false

  loop: "{{ archiver_remove_tenants }}"

- name: Disable removed ams-consumer services
  ansible.builtin.systemd_service:
    name: "ams-consumer@{{ item.tenant_name }}.service"
    enabled: false
  loop: "{{ archiver_remove_tenants }}"
