[archiver]
archiver connector_infra=dev

[archiver:vars]
ansible_user=user

[all]
archiver connector_infra=dev

[all:vars]
ansible_user=user


# [connectors]
# connectors.devel.mon.argo.grnet.gr connector_infra=dev
# connectors.mon.staging.eosc.grnet.gr connector_infra=dev
# connectors.mon.eosc.grnet.gr connector_infra=prod
# connectors.mon.argo.grnet.gr connector_infra=prod
# 
# [connectors:vars]
# ansible_user=dvrcic
# connector_monitoring_enable=true
# 
# [all]
# connectors.devel.mon.argo.grnet.gr connector_infra=dev
# connectors.mon.staging.eosc.grnet.gr connector_infra=dev
# connectors.mon.eosc.grnet.gr connector_infra=prod
# connectors.mon.argo.grnet.gr connector_infra=prod
# 
# [all:vars]
# ansible_user=dvrcic
# connector_monitoring_enable=true
# 
# [devel]
# connectors.devel.mon.argo.grnet.gr
# connectors.mon.staging.eosc.grnet.gr
# 
# [devel:vars]
# ansible_user=dvrcic
# connector_infra=dev
# connector_monitoring_enable=true
# 
# [production]
# connectors.mon.eosc.grnet.gr
# connectors.mon.argo.grnet.gr
# 
# [production:vars]
# ansible_user=dvrcic
# connector_infra=prod
# connector_monitoring_enable=true