---

- name: Set up tenants config file
  ansible.builtin.include_tasks: ./tenant-poem-conf.yml
  loop: "{{ poem_tenants }}"
  when: poem_tenants | length > 0
  loop_control:
    label: "{{ item.tenant_name }}"


- name: Set up tenants DB tables
  ansible.builtin.include_tasks: ./tenant-db-tables.yml
  loop: "{{ poem_tenants }}"
  when: poem_tenants | length > 0
  loop_control:
    label: "{{ item.tenant_name }}"


- name: Set up tokens
  ansible.builtin.include_tasks: ./tokens-tenants-set.yml
  loop: "{{ poem_tenants }}"
  when: poem_tenants | length > 0
  loop_control:
    label: "{{ item.tenant_name }}"


- name: Sync metrics from SuperPOEM
  ansible.builtin.include_tasks: ./tenant-sync-superpoem-metrics.yml
  loop: "{{ poem_tenants }}"
  when: poem_tenants | length > 0
  loop_control:
    label: "{{ item.tenant_name }}"


- name: Restart Apache
  ansible.builtin.systemd_service:
    name: httpd
    state: restarted
    daemon_reload: true


- name: Remove tenants
  ansible.builtin.include_tasks: ./remove-tenants.yml
  loop: "{{ poem_remove_tenants }}"
  when: poem_remove_tenants | length > 0
