---


- name: Check if tenant exist - {{ item }}
  ansible.builtin.shell:
    cmd: |
      source {{ poem_virtenv_path }}/bin/activate
      poem-tenant -l | grep -q {{ item }}
    chdir:
      "{{ poem_virtenv_path }}"
  register: shellresult
  ignore_errors: true
  changed_when: true


- name: Remove POEM tenant - {{ item }}
  ansible.builtin.shell:
    cmd: |
      source {{ poem_virtenv_path }}/bin/activate
      poem-tenant -t {{ item }} -r
    chdir:
      "{{ poem_virtenv_path }}"
  when: shellresult.rc == 0
  changed_when: shellresult.rc == 0


- name: Query whether RW WEB-API token exist - {{ item }}
  vars:
    ansible_python_interpreter: "{{ poem_virtenv_path }}/bin/python"
  community.postgresql.postgresql_query:
    db: "{{ poem_db_name }}"
    login_host: localhost
    login_user: "{{ poem_db_user }}"
    login_password: "{{ poem_db_password }}"
    search_path: public
    query: "SELECT 1 FROM poem_super_admin_webapikey where name='WEB-API-{{ item | upper }}'"
  register: poem_token_query
  failed_when: false


- name: Remove POEM tenant RW token - {{ item }}
  vars:
    ansible_python_interpreter: "{{ poem_virtenv_path }}/bin/python"
  community.postgresql.postgresql_query:
    db: "{{ poem_db_name }}"
    login_host: localhost
    login_user: "{{ poem_db_user }}"
    login_password: "{{ poem_db_password }}"
    search_path: public
    query: "DELETE FROM poem_super_admin_webapikey where name='WEB-API-{{ item | upper }}'"
  when: poem_token_query.rowcount == 1


- name: Query whether RO WEB-API token exist - {{ item }}
  vars:
    ansible_python_interpreter: "{{ poem_virtenv_path }}/bin/python"
  community.postgresql.postgresql_query:
    db: "{{ poem_db_name }}"
    login_host: localhost
    login_user: "{{ poem_db_user }}"
    login_password: "{{ poem_db_password }}"
    search_path: public
    query: "SELECT 1 FROM poem_super_admin_webapikey where name='WEB-API-{{ item | upper }}-RO'"
  register: poem_token_query
  failed_when: false


- name: Remove POEM tenant RO token - {{ item }}
  vars:
    ansible_python_interpreter: "{{ poem_virtenv_path }}/bin/python"
  community.postgresql.postgresql_query:
    db: "{{ poem_db_name }}"
    login_host: localhost
    login_user: "{{ poem_db_user }}"
    login_password: "{{ poem_db_password }}"
    search_path: public
    query: "DELETE FROM poem_super_admin_webapikey where name='WEB-API-{{ item | upper }}-RO'"
  when: poem_token_query.rowcount == 1
