---

- name: Set WEB-API and WEB-API-RO tokens - {{ item.tenant_name }}
  ansible.builtin.shell:
    cmd: |
      source {{ poem_virtenv_path }}/bin/activate
      poem-token webapi -t {{ item.tenant_name }} \
      -ko {{ item.tokens.webapi_ro }} \
      -kw {{ item.tokens.webapi_rw }}
    chdir:
      "{{ poem_virtenv_path }}"


- name: Set REST-API token - {{ item.tenant_name }}
  ansible.builtin.shell:
    cmd: |
      source {{ poem_virtenv_path }}/bin/activate
      poem-token restapi -t {{ item.tenant_name }} \
      -k {{ item.tokens.restapi }}
    chdir:
      "{{ poem_virtenv_path }}"
