# Ansible extra vars applied to every connector playbook run.

connector_tenant_topo_type: CSV
connector_tenant_cron_weights_disable: true
connector_tenant_cron_downtimes_disable: true
connector_tenant_bdii: false
connector_tenant_jobs:
  - name: CORE
    dirname: CORE
