# Ansible extra vars applied to every connector playbook run.

connector_tenant_cron_weights_disable: true
connector_tenant_cron_downtimes_disable: true
connector_tenant_webapi_token: "{{ connector_tokens.default.webapi }}"
connector_tenant_bdii: false
connector_tenant_jobs:
  - name: CORE
    dirname: CORE
connector_tenant_auth_useplainhttpauth: false
connector_tenant_topo_fetchtype: ServiceGroups
connector_tenant_topo_uidserviceendpoints: true

poem_tenant_superuser_name: poem
poem_tenant_superuser_password: poempass
poem_tenant_namespace: CH.CERN.SAM
poem_tenant_samlloginstring: Login using EGI CHECK-IN
poem_tenant_samlservicename: ARGO POEM EGI-CheckIN
poem_tenant_termsofuse: https://argo.egi.eu/egi/Critical/termsofUse
poem_tenant_privacypolicies: https://argo.egi.eu/egi/Critical/policies/
poem_tenant_superuser_email: argo-ggus-support@grnet.gr
